import 'package:flutter/material.dart';

Map expenseCategories = {
  'Bills': Icons.water_damage,
  'Car': Icons.directions_car,
  'Cigarette': Icons.smoking_rooms,
  'Clothing': Icons.checkroom,
  'Drinks': Icons.liquor,
  'Electronics': Icons.cable,
  'Entertainment': Icons.sports_esports,
  'Fees': Icons.attach_money,
  'Fines': Icons.gavel,
  'Fitness': Icons.fitness_center,
  'Gas': Icons.local_gas_station,
  'Gift': Icons.redeem,
  'Groceries': Icons.local_grocery_store,
  'Food': Icons.restaurant,
  'Home': Icons.home,
  'Hotel': Icons.hotel,
  'Insurance': Icons.health_and_safety,
  'Medical Services': Icons.medical_services,
  'Other': Icons.apps,
  'Parking': Icons.local_parking,
  'Pets': Icons.pets,
  'Pharmacy': Icons.medication,
  'Rent': Icons.apartment,
  'Shopping': Icons.shopping_bag,
  'Snacks': Icons.icecream,
  'Sports': Icons.sports_soccer,
  'Social': Icons.people,
  'Tax': Icons.request_quote,
  'Telephone': Icons.phone,
  'Transportation': Icons.train,
};

Map incomeCategories = {
  'Award': Icons.redeem,
  'Investment': Icons.savings,
  'Other': Icons.apps,
  'Refund': Icons.repeat,
  'Salary': Icons.payments,
};
