import 'package:flutter/material.dart';

Map expenseCategories = {
  'Bills': Icons.water_damage,
  'Car': Icons.directions_car,
  'Cigarette': Icons.smoking_rooms,
  'Clothing': Icons.checkroom,
  'Drinks': Icons.liquor,
  'Electronics': Icons.cable,
  'Entertainment': Icons.sports_esports,
  'Fees': Icons.attach_money,
  'Fines': Icons.gavel,
  'Fitness': Icons.fitness_center,
  'Gas': Icons.local_gas_station,
  'Gift': Icons.redeem,
  'Groceries': Icons.local_grocery_store,
  'Food': Icons.restaurant,
  'Home': Icons.home,
  'Hotel': Icons.hotel,
  'Insurance': Icons.health_and_safety,
  'Medical Services': Icons.medical_services,
  'Other': Icons.apps,
  'Parking': Icons.local_parking,
  'Pets': Icons.pets,
  'Pharmacy': Icons.medication,
  'Rent': Icons.apartment,
  'Shopping': Icons.shopping_bag,
  'Snacks': Icons.icecream,
  'Sports': Icons.sports_soccer,
  'Social': Icons.people,
  'Tax': Icons.request_quote,
  'Telephone': Icons.phone,
  'Transportation': Icons.train,
};

Map incomeCategories = {
  'Award': Icons.redeem,
  'Investment': Icons.savings,
  'Other': Icons.apps,
  'Refund': Icons.repeat,
  'Salary': Icons.payments,
};

Map currenciesSymbolic = {
  'AED': ['United Arab Emirates Dirham', '🇦🇪'],
  'AFN': ['Afghan Afghani', '🇦🇫'],
  'ALL': ['Albanian Lek', '🇦🇱'],
  'AMD': ['Armenian Dram', '🇦🇲'],
  'ANG': ['Netherlands Antillean Guilder', '🇧🇶'],
  'AOA': ['Angolan Kwanza', '🇦🇴'],
  'ARS': ['Argentine Peso', '🇦🇷'],
  'AUD': ['Australian Dollar', '🇦🇺'],
  'AWG': ['Aruban Florin', '🇦🇼'],
  'AZN': ['Azerbaijani Manat', '🇦🇿'],
  'BAM': ['Bosnia-Herzegovina Convertible Mark', '🇧🇦'],
  'BBD': ['Barbadian Dollar', '🇧🇧'],
  'BDT': ['Bangladeshi Taka', '🇧🇩'],
  'BGN': ['Bulgarian Lev', '🇧🇬'],
  'BHD': ['Bahraini Dinar', '🇧🇭'],
  'BIF': ['Burundian Franc', '🇧🇮'],
  'BMD': ['Bermudian Dollar', '🇧🇲'],
  'BND': ['Brunei Dollar', '🇧🇳'],
  'BOB': ['Bolivian Boliviano', '🇧🇴'],
  'BRL': ['Brazilian Real', '🇧🇷'],
  'BSD': ['Bahamian Dollar', '🇧🇸'],
  'BTN': ['Bhutanese Ngultrum', '🇧🇹'],
  'BWP': ['Botswana Pula', '🇧🇼'],
  'BYN': ['Belarusian Ruble', '🇧🇾'],
  'BZD': ['Belize Dollar', '🇧🇿'],
  'CAD': ['Canadian Dollar', '🇨🇦'],
  'CDF': ['Congolese Franc', '🇨🇩'],
  'CHF': ['Swiss Franc', '🇨🇭'],
  'CLP': ['Chilean Peso', '🇨🇱'],
  'CNY': ['Chinese Yuan', '🇨🇳'],
  'COP': ['Colombian peso', '🇨🇴'],
  'CRC': ['Costa Rican Colón', '🇨🇷'],
  'CUP': ['Cuban Peso', '🇨🇺'],
  'CVE': ['Cape Verdean Escudo', '🇨🇻'],
  'CZK': ['Czech Koruna', '🇨🇿'],
  'DJF': ['Djiboutian Franc', '🇩🇯'],
  'DKK': ['Danish Krone', '🇩🇰'],
  'DOP': ['Dominican Peso', '🇩🇴'],
  'DZD': ['Algerian Dinar', '🇩🇿'],
  'EGP': ['Egyptian Pound', '🇪🇬'],
  'ERN': ['Eritrean Nakfa', '🇪🇷'],
  'ETB': ['Ethiopian Birr', '🇪🇹'],
  'EUR': ['Euro', '🇪🇺'],
  'FJD': ['Fijian Dollar', '🇫🇯'],
  'FKP': ['Falkland Islands Pound', '🇫🇰'],
  'GBP': ['British Pound', '🇬🇧'],
  'GEL': ['Georgian Lari', '🇬🇪'],
  'GHS': ['Ghanaian Cedi', '🇬🇭'],
  'GIP': ['Gibraltar Pound', '🇬🇮'],
  'GMD': ['Gambian Dalasi', '🇬🇲'],
  'GNF': ['Guinean Franc', '🇬🇳'],
  'GTQ': ['Guatemalan Quetzal', '🇬🇹'],
  'GYD': ['Guyanese Dollar', '🇬🇾'],
  'HKD': ['Hong Kong Dollar', '🇭🇰'],
  'HNL': ['Honduran Lempira', '🇭🇳'],
  'HRK': ['Croatian Kuna', '🇭🇷'],
  'HTG': ['Haitian Gourde', '🇭🇹'],
  'HUF': ['Hungarian Forint', '🇭🇺'],
  'IDR': ['Indonesian Rupiah', '🇮🇩'],
  'ILS': ['Israeli New Shekel', '🇮🇱'],
  'INR': ['Indian Rupee', '🇮🇳'],
  'IQD': ['Iraqi Dinar', '🇮🇶'],
  'IRR': ['Iranian Rial', '🇮🇷'],
  'ISK': ['Icelandic Króna', '🇮🇸'],
  'JMD': ['Jamaican Dollar', '🇯🇲'],
  'JOD': ['Jordanian Dinar', '🇯🇴'],
  'JPY': ['Japanese Yen', '🇯🇵'],
  'KES': ['Kenyan Shilling', '🇰🇪'],
  'KGS': ['Kyrgyzstani Som', '🇰🇬'],
  'KHR': ['Cambodian Riel', '🇰🇭'],
  'KMF': ['Comorian Franc', '🇰🇲'],
  'KPW': ['North Korean Won', '🇰🇵'],
  'KRW': ['South Korean Won', '🇰🇷'],
  'KWD': ['Kuwaiti Dinar', '🇰🇼'],
  'KYD': ['Cayman Islands Dollar', '🇰🇾'],
  'KZT': ['Kazakhstani Tenge', '🇰🇿'],
  'LAK': ['Lao Kip', '🇱🇦'],
  'LBP': ['Lebanese Pound', '🇱🇧'],
  'LKR': ['Sri Lankan Rupee', '🇱🇰'],
  'LRD': ['Liberian Dollar', '🇱🇷'],
  'LSL': ['Lesotho Loti', '🇱🇸'],
  'LYD': ['Libyan Dinar', '🇱🇾'],
  'MAD': ['Moroccan Dirham', '🇲🇦'],
  'MDL': ['Moldovan Leu', '🇲🇩'],
  'MGA': ['Malagasy Ariary', '🇲🇬'],
  'MKD': ['Macedonian denar', '🇲🇰'],
  'MMK': ['Burmese Kyat', '🇲🇲'],
  'MNT': ['Mongolian Tögrög', '🇲🇳'],
  'MOP': ['Macanese Pataca', '🇲🇴'],
  'MRU': ['Mauritanian Ouguiya', '🇲🇷'],
  'MUR': ['Mauritian Rupee', '🇲🇺'],
  'MVR': ['Maldivian Rufiyaa', '🇲🇻'],
  'MWK': ['Malawian Kwacha', '🇲🇼'],
  'MXN': ['Mexican Peso', '🇲🇽'],
  'MYR': ['Malaysian Ringgit', '🇲🇾'],
  'MZN': ['Mozambican Metical', '🇲🇿'],
  'NAD': ['Namibian Dollar', '🇳🇦'],
  'NGN': ['Nigerian Naira', '🇳🇬'],
  'NIO': ['Nicaraguan Córdoba', '🇳🇮'],
  'NOK': ['Norwegian Krone', '🇳🇴'],
  'NPR': ['Nepalese Rupee', '🇳🇵'],
  'NZD': ['New Zealand Dollar', '🇳🇿'],
  'OMR': ['Omani Rial', '🇴🇲'],
  'PAB': ['Panamanian Balboa', '🇵🇦'],
  'PEN': ['Peruvian Sol', '🇵🇪'],
  'PGK': ['Papua New Guinean Kina', '🇵🇬'],
  'PHP': ['Philippine Peso', '🇵🇭'],
  'PKR': ['Pakistani Rupee', '🇵🇰'],
  'PLN': ['Polish Złoty', '🇵🇱'],
  'PYG': ['Paraguayan Guaraní', '🇵🇾'],
  'QAR': ['Qatari Riyal', '🇶🇦'],
  'RON': ['Romanian Leu', '🇷🇴'],
  'RSD': ['Serbian Dinar', '🇷🇸'],
  'RUB': ['Russian Ruble', '🇷🇺'],
  'RWF': ['Rwandan Franc', '🇷🇼'],
  'SAR': ['Saudi Riyal', '🇸🇦'],
  'SBD': ['Solomon Islands Dollar', '🇸🇧'],
  'SCR': ['Seychellois Rupee', '🇸🇨'],
  'SDG': ['Sudanese Pound', '🇸🇩'],
  'SEK': ['Swedish Krona', '🇸🇪'],
  'SGD': ['Singapore Dollar', '🇸🇬'],
  'SHP': ['Saint Helena Pound', '🇦🇨'],
  'SLL': ['Sierra Leonean Leone', '🇸🇱'],
  'SOS': ['Somali Shilling', '🇸🇴'],
  'SRD': ['Surinamese Dollar', '🇸🇷'],
  'SSP': ['South Sudanese Pound', '🇸🇸'],
  'STN': ['São Tomé and Príncipe Dobra', '🇸🇹'],
  'SYP': ['Syrian Pound', '🇸🇾'],
  'SZL': ['Swazi Lilangeni', '🇸🇿'],
  'THB': ['Thai Baht', '🇹🇭'],
  'TJS': ['Tajikistani Somoni', '🇹🇯'],
  'TMT': ['Turkmenistan Manat', '🇹🇲'],
  'TND': ['Tunisian Dinar', '🇹🇳'],
  'TOP': ['Tongan Paʻanga', '🇹🇴'],
  'TRY': ['Turkish Lira', '🇹🇷'],
  'TTD': ['Trinidad and Tobago Dollar', '🇹🇹'],
  'TWD': ['New Taiwan Dollar', '🇹🇼'],
  'TZS': ['Tanzanian Shilling', '🇹🇿'],
  'UAH': ['Ukrainian Hryvnia', '🇺🇦'],
  'UGX': ['Ugandan Shilling', '🇺🇬'],
  'USD': ['United States Dollar', '🇺🇸'],
  'UYU': ['Uruguayan Peso', '🇺🇾'],
  'UZS': ['Uzbekistani Soʻm', '🇺🇿'],
  'VES': ['Venezuelan Bolívar Soberano', '🇻🇪'],
  'VND': ['Vietnamese Đồng', '🇻🇳'],
  'VUV': ['Vanuatu Vatu', '🇻🇺'],
  'WST': ['Samoan Tālā', '🇼🇸'],
  'XAF': ['Central African CFA Franc', '🇨🇫'],
  'XCD': ['Eastern Caribbean Dollar', '🇩🇲'],
  'XOF': ['West African CFA Franc', '🇳🇪'],
  'XPF': ['CFP Franc', '🇵🇫'],
  'YER': ['Yemeni Rial', '🇾🇪'],
  'ZAR': ['South African Rand', '🇿🇦'],
  'ZMW': ['Zambian Kwacha', '🇿🇲'],
};

List months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
];
